// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNlibod74J7tj-Fn3DeMmeFpIwhmJFvs',
    appId: '1:421450016212:web:da8dcfb741215addf8e241',
    messagingSenderId: '421450016212',
    projectId: 'forest-61891',
    authDomain: 'forest-61891.firebaseapp.com',
    storageBucket: 'forest-61891.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA00cA1BjzTJRzzLLl5snty2aW618Pzuio',
    appId: '1:421450016212:android:fec97fea690e8308f8e241',
    messagingSenderId: '421450016212',
    projectId: 'forest-61891',
    storageBucket: 'forest-61891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjSkhM-fopVlZmIOovqcSQvx4uW4HF-E',
    appId: '1:421450016212:ios:c12be2caaf192660f8e241',
    messagingSenderId: '421450016212',
    projectId: 'forest-61891',
    storageBucket: 'forest-61891.firebasestorage.app',
    iosBundleId: 'com.example.focusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmjSkhM-fopVlZmIOovqcSQvx4uW4HF-E',
    appId: '1:421450016212:ios:c12be2caaf192660f8e241',
    messagingSenderId: '421450016212',
    projectId: 'forest-61891',
    storageBucket: 'forest-61891.firebasestorage.app',
    iosBundleId: 'com.example.focusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdNlibod74J7tj-Fn3DeMmeFpIwhmJFvs',
    appId: '1:421450016212:web:ac7165cee1a6db93f8e241',
    messagingSenderId: '421450016212',
    projectId: 'forest-61891',
    authDomain: 'forest-61891.firebaseapp.com',
    storageBucket: 'forest-61891.firebasestorage.app',
  );
}
