// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-zgdJ08hthIDdRQ7E4rDCvUXvnocz-Mc',
    appId: '1:881084146590:web:81fbac9a5ec69e50422c8f',
    messagingSenderId: '881084146590',
    projectId: 'forest-focus-app-594dc',
    authDomain: 'forest-focus-app-594dc.firebaseapp.com',
    storageBucket: 'forest-focus-app-594dc.firebasestorage.app',
    measurementId: 'G-45NF5WKZNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEmlxJal0ZGVqu_W5hzk7JddnZCyBgljY',
    appId: '1:881084146590:android:f3914d608bb2824d422c8f',
    messagingSenderId: '881084146590',
    projectId: 'forest-focus-app-594dc',
    storageBucket: 'forest-focus-app-594dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCso4nU7r6WeaTCibkcVR9ZJR-ZdLdh8',
    appId: '1:881084146590:ios:c154d5c14f034c5d422c8f',
    messagingSenderId: '881084146590',
    projectId: 'forest-focus-app-594dc',
    storageBucket: 'forest-focus-app-594dc.firebasestorage.app',
    iosBundleId: 'com.example.focusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASCso4nU7r6WeaTCibkcVR9ZJR-ZdLdh8',
    appId: '1:881084146590:ios:c154d5c14f034c5d422c8f',
    messagingSenderId: '881084146590',
    projectId: 'forest-focus-app-594dc',
    storageBucket: 'forest-focus-app-594dc.firebasestorage.app',
    iosBundleId: 'com.example.focusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-zgdJ08hthIDdRQ7E4rDCvUXvnocz-Mc',
    appId: '1:881084146590:web:f2ff56ec8c676931422c8f',
    messagingSenderId: '881084146590',
    projectId: 'forest-focus-app-594dc',
    authDomain: 'forest-focus-app-594dc.firebaseapp.com',
    storageBucket: 'forest-focus-app-594dc.firebasestorage.app',
    measurementId: 'G-ZJMTZHFRTN',
  );
}
